name: CI

on:
  push:
    branches: [ "main", "production", "dev" ]
  pull_request:
    branches: [ "main", "production", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Python 3.10 for compatibility

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev build-essential

      # Upgrade pip and install essential build tools
      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cython

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install torch==1.12.1 torchvision==0.13.1 tensorboardx==2.5.1 scipy==1.9.3 pyyaml==6.0 easydict==1.9 pytest

      # Run Python test cases
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings
