name: CI

on:
  push:
    branches: [ "main", "production", "dev" ]
  pull_request:
    branches: [ "main", "production", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install system dependencies for PyYAML
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev build-essential

      # Upgrade pip and install build tools
      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cython  # Ensure build tools are available

      # Override PyYAML version for compatibility
      - name: Install compatible PyYAML version
        run: |
          pip install pyyaml==6.0  # Install a compatible PyYAML version

      # Install remaining dependencies from requirements.txt
      - name: Install dependencies (ignore PyYAML conflict)
        run: |
          pip install --no-deps -r requirements.txt  # Ignore dependencies for pre-installed packages

      # Run Python test cases
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings
