name: CI

on:
  push:
    branches: [ "main", "production", "dev" ]
  pull_request:
    branches: [ "main", "production", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use a compatible Python version

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libyaml-dev  # Install build tools and libyaml for PyYAML

      # Upgrade pip and install essential build tools
      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cython  # Ensure build tools are installed

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install your project's dependencies

      # Run Python test cases
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings
